image: "docker:latest"

stages:
  - compile
  - build
  - release
  - deploy

services:
- docker:dind

variables:
  DOCKER_DRIVER: overlay

.docker_before: &docker_before
  - "pwd"
  - "docker info"
  - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME/$CI_PIPELINE_ID"
  paths:
    - /

composer:
  stage: compile
  tags:
    - docker
  image: gitlab.kodeks.ru:4567/docker/composer
  script:
    - php -r "file_exists('.env') || copy('.env.example', '.env');"
    - composer install
    - php artisan key:generate
    - ls -la

build:
  stage: build
  tags:
    - docker
  before_script: *docker_before
  script:
    - ls -la
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME

release-latest:
  stage: release
  tags:
    - docker
  before_script: *docker_before
  script:
    - ls -la
    - docker pull $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
    - docker tag $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker rmi $CI_REGISTRY_IMAGE:latest
  only:
    - master

.deploy: &deploy
    stage: deploy
    tags:
        - docker
    script:
      - ls -la
      - ls -la deploy
      - cd deploy && ./rancher-compose --url $RANCHER_URL --access-key $RANCHER_KEY --secret-key $RANCHER_SECRET
        -p $CI_PROJECT_NAME -e .env up --upgrade --confirm-upgrade --force-upgrade -d

deploy_dev:
      <<: *deploy
      variables:
        RANCHER_URL: $RANCHER_URL_DEV
        RANCHER_KEY: $RANCHER_KEY_DEV
        RANCHER_SECRET: $RANCHER_SECRET_DEV
      environment:
        name: dev
      only:
        - dev
        - develop
        - master