image: "docker:latest"

stages:
  - compile
  - build
  - release

services:
- docker:dind

variables:
  DOCKER_DRIVER: overlay

.docker_before: &docker_before
  - "pwd"
  - "docker info"
  - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"

.docker_after: &docker_after
  - "docker images"
  - "docker logout $CI_REGISTRY"

composer:
  stage: compile
  tags:
    - docker
  image: gitlab.kodeks.ru:4567/docker/composer
  script:
    - install

build:
  stage: build
  tags:
    - docker
  script:
    <<- *docker_before
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
    <<- *docker_after

release-latest:
  stage: release
  tags:
    - docker
  script:
    <<- *docker_before
    - docker pull $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
    - docker tag $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker rmi $CI_REGISTRY_IMAGE:latest
    <<- *docker_after
  only:
    - master